name: Cypress Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      GITHUB_EMAIL: ${{ secrets.LOGIN_GITHUB_EMAIL }}
      GITHUB_PASSWORD: ${{ secrets.LOGIN_GITHUB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: cypress-e2e
        run: npm install

      - name: Run Cypress tests
        working-directory: cypress-e2e
        run: npm run test